### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by yanqingming** [xurui-joei/DBCTNet#1]
尊敬的作者大大您好！
最近有幸拜读您的高光谱分类论文，我也在做关于高光谱分类的相关研究工作，最近计算网络模型的flops有点疑问但是关于flops的计算有些小小疑问
加入我现在针对paviau数据集做flops的计算也就是batchsize大小为128，patch大小为9，通道数为103
for inputs, labels in test_loader:
    inputs = inputs.to(device)
    start_time = time.time()
    outputs = model(inputs)
    flops, params = profile(model, inputs=(inputs,))
    print('FLOPs = ' + str(flops / 1000 ** 2) + 'M')
    print('FLOPs: %.2f M, Params: %.2f k' % (flops / (1e6), params / 1e3))
利用profile库,其中无论inputs是tensor(1,1,9,9,103)6.25M还是(128,1,9,9,103)800.11 M都有点过大或过小与论文里的26.363M不成比例关系估计是我做的哪地方有了问题,也可能不太理解flops所计算的标准
其中model为您的DBCTnet,然后参数量是一致的,还请您指点一二

**Comment by xurui-joei** [comment]
你好。文章中的flops结果是使用fvscore库在batch_size为4下得到的。

**Comment by xurui-joei** [comment]
> 尊敬的作者大大您好！ 最近有幸拜读您的高光谱分类论文，我也在做关于高光谱分类的相关研究工作，最近计算网络模型的flops有点疑问但是关于flops的计算有些小小疑问 加入我现在针对paviau数据集做flops的计算也就是batchsize大小为128，patch大小为9，通道数为103 for inputs, labels in test_loader: inputs = inputs.to(device) start_time = time.time() outputs = model(inputs) flops, params = profile(model, inputs=(inputs,)) print('FLOPs = ' + str(flops / 1000 ** 2) + 'M') print('FLOPs: %.2f M, Params: %.2f k' % (flops / (1e6), params / 1e3)) 利用profile库,其中无论inputs是tensor(1,1,9,9,103)6.25M还是(128,1,9,9,103)800.11 M都有点过大或过小与论文里的26.363M不成比例关系估计是我做的哪地方有了问题,也可能不太理解flops所计算的标准 其中model为您的DBCTnet,然后参数量是一致的,还请您指点一二

你好。文章中的flops结果是使用fvscore库在batch_size为4下得到的。

**Comment by yanqingming** [comment]
好的收到谢谢啦祝您学术长青
&nbsp;


言清铭
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月25日(星期二) 上午9:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xurui-joei/DBCTNet] 求助 (Issue #1)














  
尊敬的作者大大您好！ 最近有幸拜读您的高光谱分类论文，我也在做关于高光谱分类的相关研究工作，最近计算网络模型的flops有点疑问但是关于flops的计算有些小小疑问 加入我现在针对paviau数据集做flops的计算也就是batchsize大小为128，patch大小为9，通道数为103 for inputs, labels in test_loader: inputs = inputs.to(device) start_time = time.time() outputs = model(inputs) flops, params = profile(model, inputs=(inputs,)) print('FLOPs = ' + str(flops / 1000 ** 2) + 'M') print('FLOPs: %.2f M, Params: %.2f k' % (flops / (1e6), params / 1e3)) 利用profile库,其中无论inputs是tensor(1,1,9,9,103)6.25M还是(128,1,9,9,103)800.11 M都有点过大或过小与论文里的26.363M不成比例关系估计是我做的哪地方有了问题,也可能不太理解flops所计算的标准 其中model为您的DBCTnet,然后参数量是一致的,还请您指点一二
  
你好。文章中的flops结果是使用fvscore库在batch_size为4下得到的。

**Comment by xurui-joei** [comment]
> 好的收到谢谢啦祝您学术长青 &nbsp; 言清铭 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年6月25日(星期二) 上午9:51 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [xurui-joei/DBCTNet] 求助 (Issue #1) 尊敬的作者大大您好！ 最近有幸拜读您的高光谱分类论文，我也在做关于高光谱分类的相关研究工作，最近计算网络模型的flops有点疑问但是关于flops的计算有些小小疑问 加入我现在针对paviau数据集做flops的计算也就是batchsize大小为128，patch大小为9，通道数为103 for inputs, labels in test_loader: inputs = inputs.to(device) start_time = time.time() outputs = model(inputs) flops, params = profile(model, inputs=(inputs,)) print('FLOPs = ' + str(flops / 1000 ** 2) + 'M') print('FLOPs: %.2f M, Params: %.2f k' % (flops / (1e6), params / 1e3)) 利用profile库,其中无论inputs是tensor(1,1,9,9,103)6.25M还是(128,1,9,9,103)800.11 M都有点过大或过小与论文里的26.363M不成比例关系估计是我做的哪地方有了问题,也可能不太理解flops所计算的标准 其中model为您的DBCTnet,然后参数量是一致的,还请您指点一二 你好。文章中的flops结果是使用fvscore库在batch_size为4下得到的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

不好意思，更正一下，是fvcore库

**Comment by yanqingming** [comment]
学长俺又来打扰啦,俺想问一个愚蠢的问题,推理时间还是针对一个固定批次的patch数据,还是test_data,还是整个all_data呢

言清铭
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xurui-joei/DBCTNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月26日(星期三) 上午9:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xurui-joei/DBCTNet] 求助 (Issue #1)





  
好的收到谢谢啦祝您学术长青 &nbsp; 言清铭 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2024年6月25日(星期二) 上午9:51 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [xurui-joei/DBCTNet] 求助 (Issue #1) 尊敬的作者大大您好！ 最近有幸拜读您的高光谱分类论文，我也在做关于高光谱分类的相关研究工作，最近计算网络模型的flops有点疑问但是关于flops的计算有些小小疑问 加入我现在针对paviau数据集做flops的计算也就是batchsize大小为128，patch大小为9，通道数为103 for inputs, labels in test_loader: inputs = inputs.to(device) start_time = time.time() outputs = model(inputs) flops, params = profile(model, inputs=(inputs,)) print('FLOPs = ' + str(flops / 1000 ** 2) + 'M') print('FLOPs: %.2f M, Params: %.2f k' % (flops / (1e6), params / 1e3)) 利用profile库,其中无论inputs是tensor(1,1,9,9,103)6.25M还是(128,1,9,9,103)800.11 M都有点过大或过小与论文里的26.363M不成比例关系估计是我做的哪地方有了问题,也可能不太理解flops所计算的标准 其中model为您的DBCTnet,然后参数量是一致的,还请您指点一二 你好。文章中的flops结果是使用fvscore库在batch_size为4下得到的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
不好意思，更正一下，是fvcore库

**Comment by xurui-joei** [comment]
> 学长俺又来打扰啦,俺想问一个愚蠢的问题,推理时间还是针对一个固定批次的patch数据,还是test_data,还是整个all_data呢 言清铭 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xurui-joei/DBCTNet" ***@***.***&gt;; 发送时间:&nbsp;2024年6月26日(星期三) 上午9:11 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [xurui-joei/DBCTNet] 求助 (Issue #1) 好的收到谢谢啦祝您学术长青 &nbsp; 言清铭 @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2024年6月25日(星期二) 上午9:51 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [xurui-joei/DBCTNet] 求助 (Issue #1) 尊敬的作者大大您好！ 最近有幸拜读您的高光谱分类论文，我也在做关于高光谱分类的相关研究工作，最近计算网络模型的flops有点疑问但是关于flops的计算有些小小疑问 加入我现在针对paviau数据集做flops的计算也就是batchsize大小为128，patch大小为9，通道数为103 for inputs, labels in test_loader: inputs = inputs.to(device) start_time = time.time() outputs = model(inputs) flops, params = profile(model, inputs=(inputs,)) print('FLOPs = ' + str(flops / 1000 ** 2) + 'M') print('FLOPs: %.2f M, Params: %.2f k' % (flops / (1e6), params / 1e3)) 利用profile库,其中无论inputs是tensor(1,1,9,9,103)6.25M还是(128,1,9,9,103)800.11 M都有点过大或过小与论文里的26.363M不成比例关系估计是我做的哪地方有了问题,也可能不太理解flops所计算的标准 其中model为您的DBCTnet,然后参数量是一致的,还请您指点一二 你好。文章中的flops结果是使用fvscore库在batch_size为4下得到的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 不好意思，更正一下，是fvcore库 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你好，文中推理时间在测试集上推理得到
