### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by codemanvon30** [xurui-joei/DBCTNet#2]
作者大大你好，能否給我提供你跑的对比实验的所有代码呢，本人现在缺少一个整合好的对比实验的代码，可以发一下吗

**Comment by xurui-joei** [comment]
你好。可以修改train_test.py，调用需要对比的模型即可。

**Comment by dhjshinidie** [comment]
作者大大，你的DBCTNet模型 跑Huston2013时的实验结果跟论文不符合呀，求解答

**Comment by xurui-joei** [comment]
> 作者大大，你的DBCTNet模型 跑Huston2013时的实验结果跟论文不符合呀，求解答

你好。不同实验环境、模型训练的随机性以及数据集划分的随机性都会产生不同程度的结果差异。

**Comment by dhjshinidie** [comment]
作者大大，可我用你的模型跑PU和LK都与论文一致，就是Hs精度差距很大呀

**Comment by xurui-joei** [comment]
> 作者大大，可我用你的模型跑PU和LK都与论文一致，就是Hs精度差距很大呀

请问你HS的OA大概是多少呢

**Comment by dhjshinidie** [comment]
是89左右

**Comment by xurui-joei** [comment]
> 是89左右

HS标准数据集上89左右都是正常的。HS的标准数据集难度更高，文章里的HS结果是随机划分的，不同数据集划分会导致不同结果。

**Comment by dhjshinidie** [comment]
好的，谢谢作者大大，请问作者大大论文结尾说分支之间没有交互模块，说明模型有进一步增强的潜力，想问一下作者大大是否正在这个方向努力呀

**Comment by xurui-joei** [comment]
> 好的，谢谢作者大大，请问作者大大论文结尾说分支之间没有交互模块，说明模型有进一步增强的潜力，想问一下作者大大是否正在这个方向努力呀

我暂时没再继续做这一块了。最开始有试过设计类似Conformer那样的CNN分支与TE分支的交互模块，但结果会下降。需要设计合适的交互模块才行。

**Comment by dhjshinidie** [comment]
作者大大你好，打扰你了，请问你的论文里3d的光谱图是用什么软件获得的鸭

**Comment by xurui-joei** [comment]
> 作者大大你好，打扰你了，请问你的论文里3d的光谱图是用什么软件获得的鸭

你好，使用python画的，借助spectral 和 ipython
