### ISSUE TITLE
对比实验

### ISSUE THREAD

**Issue by NinJiaA** [xurui-joei/DBCTNet#6]
大佬你好，我和你选取了相同的对比实验，但我用其git开源的代码跑时，精度和你文章里写的低了5到9个点，我想可能是因为我采用的是原模型的训练策略。请问你可以分享你整合的9个对比实验的代码给我吗，一顿火锅奉上，q2352335839。

**Comment by xurui-joei** [comment]
> 大佬你好，我和你选取了相同的对比实验，但我用其git开源的代码跑时，精度和你文章里写的低了5到9个点，我想可能是因为我采用的是原模型的训练策略。请问你可以分享你整合的9个对比实验的代码给我吗，一顿火锅奉上，q2352335839。

你好，训练的超参可以在文章实验部分找到。由于高光谱数据集很多时候都是随机划分train，val，test的，所以结果上会有一定程度的区别
